//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Language.Language_en-US", typeof(Language_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the settings database.
        /// </summary>
        public static string ActualizeSettingsErrorCaption {
            get {
                return ResourceManager.GetString("ActualizeSettingsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string AddPhotoHostOrHostess {
            get {
                return ResourceManager.GetString("AddPhotoHostOrHostess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZadGestion already installed on another computer.
        /// </summary>
        public static string AlreadyInstalledCaption {
            get {
                return ResourceManager.GetString("AlreadyInstalledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZadGestion is already installed on another computer. Please go to https://app.Zad Gestion.com/
        ///User profile - Credentials - New computer.
        /// </summary>
        public static string AlreadyInstalledText {
            get {
                return ResourceManager.GetString("AlreadyInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive mission.
        /// </summary>
        public static string ArchiveMission {
            get {
                return ResourceManager.GetString("ArchiveMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive mission.
        /// </summary>
        public static string ArchiveMissionCaption {
            get {
                return ResourceManager.GetString("ArchiveMissionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to archive the mission?.
        /// </summary>
        public static string ArchiveMissionText {
            get {
                return ResourceManager.GetString("ArchiveMissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of birth.
        /// </summary>
        public static string BirthCity {
            get {
                return ResourceManager.GetString("BirthCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following fields are blank : .
        /// </summary>
        public static string BlankFields {
            get {
                return ResourceManager.GetString("BlankFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank fields.
        /// </summary>
        public static string BlankFieldsTitle {
            get {
                return ResourceManager.GetString("BlankFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving the client in progress....
        /// </summary>
        public static string ClientArchivePrincipalMessage {
            get {
                return ResourceManager.GetString("ClientArchivePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the client is being archived.
        /// </summary>
        public static string ClientArchiveSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientArchiveSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string ClientCompanyName {
            get {
                return ResourceManager.GetString("ClientCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number associated to the company.
        /// </summary>
        public static string ClientCompanyNumber {
            get {
                return ResourceManager.GetString("ClientCompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete client.
        /// </summary>
        public static string ClientConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("ClientConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected client ?.
        /// </summary>
        public static string ClientConfirmDeleteText {
            get {
                return ResourceManager.GetString("ClientConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the client in progress....
        /// </summary>
        public static string ClientCreationPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientCreationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is currently created and saved in the database, please wait until this window closes automatically.
        /// </summary>
        public static string ClientCreationSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientCreationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of the client in progress....
        /// </summary>
        public static string ClientDeletionPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientDeletionPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is currently deleted, please wait until this window closes automatically.
        /// </summary>
        public static string ClientDeletionSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientDeletionSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch emailing default application...
        /// </summary>
        public static string ClientEmailPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientEmailPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an emailing application is installed on your machine, the application is launching, please wait.
        /// </summary>
        public static string ClientEmailSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientEmailSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of the client statement in progress....
        /// </summary>
        public static string ClientExcelGenerationPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientExcelGenerationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait during the generation of the client statement until Microsoft Excel® is opened.
        /// </summary>
        public static string ClientExcelGenerationSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientExcelGenerationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Skype application....
        /// </summary>
        public static string ClientPhonePrincipalMessage {
            get {
                return ResourceManager.GetString("ClientPhonePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Skype is installed on your machine, the application is launching, please wait.
        /// </summary>
        public static string ClientPhoneSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientPhoneSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration the client in progress....
        /// </summary>
        public static string ClientRestorePrincipalMessage {
            get {
                return ResourceManager.GetString("ClientRestorePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the client is being restored .
        /// </summary>
        public static string ClientRestoreSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientRestoreSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a client.
        /// </summary>
        public static string ClientSelectedError {
            get {
                return ResourceManager.GetString("ClientSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client selected.
        /// </summary>
        public static string ClientSelectedErrorCaption {
            get {
                return ResourceManager.GetString("ClientSelectedErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of the clients&apos; statement in progress....
        /// </summary>
        public static string ClientsExcelGenerationPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientsExcelGenerationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait during the generation of the clients&apos; statement until Microsoft Excel® is opened.
        /// </summary>
        public static string ClientsExcelGenerationSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientsExcelGenerationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived clients....
        /// </summary>
        public static string ClientsShowArchivedPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientsShowArchivedPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment of the archived clients, please wait until this window closes.
        /// </summary>
        public static string ClientsShowArchivedSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientsShowArchivedSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress clients....
        /// </summary>
        public static string ClientsShowInProgressPrincipalMessage {
            get {
                return ResourceManager.GetString("ClientsShowInProgressPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment of the in progress clients, please wait until this window closes.
        /// </summary>
        public static string ClientsShowInProgressSecondaryMessage {
            get {
                return ResourceManager.GetString("ClientsShowInProgressSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients&apos; statement.
        /// </summary>
        public static string ClientsStatement {
            get {
                return ResourceManager.GetString("ClientsStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients&apos; statement not generated.
        /// </summary>
        public static string ClientsStatementExcelGenerationFailedCaption {
            get {
                return ResourceManager.GetString("ClientsStatementExcelGenerationFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clients&apos; statement could not have been generated. If this happens again, please contact the client support..
        /// </summary>
        public static string ClientsStatementExcelGenerationFailedText {
            get {
                return ResourceManager.GetString("ClientsStatementExcelGenerationFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open Skype to call your contact ?.
        /// </summary>
        public static string ConfirmSkypeCall {
            get {
                return ResourceManager.GetString("ConfirmSkypeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype call asked.
        /// </summary>
        public static string ConfirmSkypeCallCaption {
            get {
                return ResourceManager.GetString("ConfirmSkypeCallCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity error.
        /// </summary>
        public static string ConnectivityErrorCaption {
            get {
                return ResourceManager.GetString("ConnectivityErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to internet, please verify your configuration.
        /// </summary>
        public static string ConnectivityErrorText {
            get {
                return ResourceManager.GetString("ConnectivityErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to internet lost.
        /// </summary>
        public static string ConnectivityLostCaption {
            get {
                return ResourceManager.GetString("ConnectivityLostCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to internet lost. Please, verify your configuration. Unable to save your work while the connection is not effective.
        /// </summary>
        public static string ConnectivityLostText {
            get {
                return ResourceManager.GetString("ConnectivityLostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue ?.
        /// </summary>
        public static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate name.
        /// </summary>
        public static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate number.
        /// </summary>
        public static string CorporateNumber {
            get {
                return ResourceManager.GetString("CorporateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create host or hostess.
        /// </summary>
        public static string CreateHostOrHostess {
            get {
                return ResourceManager.GetString("CreateHostOrHostess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an mission.
        /// </summary>
        public static string CreateMission {
            get {
                return ResourceManager.GetString("CreateMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database definition.
        /// </summary>
        public static string DatabaseDefinition {
            get {
                return ResourceManager.GetString("DatabaseDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while modifying the database definition.
        /// </summary>
        public static string DatabaseDefinitionModificationErrorCaption {
            get {
                return ResourceManager.GetString("DatabaseDefinitionModificationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database modification confirmation.
        /// </summary>
        public static string DatabaseModificationConfirmationCaption {
            get {
                return ResourceManager.GetString("DatabaseModificationConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to want to modify the database definition ?.
        /// </summary>
        public static string DatabaseModificationConfirmationText {
            get {
                return ResourceManager.GetString("DatabaseModificationConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated account.
        /// </summary>
        public static string DeactivatedAccountCaption {
            get {
                return ResourceManager.GetString("DeactivatedAccountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is deactivated.  Please contact the customer service.
        /// </summary>
        public static string DeactivatedAccountText {
            get {
                return ResourceManager.GetString("DeactivatedAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the mission.
        /// </summary>
        public static string DeleteMission {
            get {
                return ResourceManager.GetString("DeleteMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed description.
        /// </summary>
        public static string DetailedDescription {
            get {
                return ResourceManager.GetString("DetailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string DriverLicence {
            get {
                return ResourceManager.GetString("DriverLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate the mission.
        /// </summary>
        public static string DuplicateMission {
            get {
                return ResourceManager.GetString("DuplicateMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit host or hostess.
        /// </summary>
        public static string EditHostOrHostess {
            get {
                return ResourceManager.GetString("EditHostOrHostess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the mission.
        /// </summary>
        public static string EditMission {
            get {
                return ResourceManager.GetString("EditMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Excel®.
        /// </summary>
        public static string ExcelImport {
            get {
                return ResourceManager.GetString("ExcelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel® not installed.
        /// </summary>
        public static string ExcelNotPresentErrorCaption {
            get {
                return ResourceManager.GetString("ExcelNotPresentErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel® is not present, please install it before using ZadGestion.
        /// </summary>
        public static string ExcelNotPresentErrorText {
            get {
                return ResourceManager.GetString("ExcelNotPresentErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generalities.
        /// </summary>
        public static string Generalities {
            get {
                return ResourceManager.GetString("Generalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate an Excel® statement.
        /// </summary>
        public static string GenerateExcelStatement {
            get {
                return ResourceManager.GetString("GenerateExcelStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host and hostess.
        /// </summary>
        public static string HostAndHostess {
            get {
                return ResourceManager.GetString("HostAndHostess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the import.
        /// </summary>
        public static string HostAndHostessExcelImportEndedCaption {
            get {
                return ResourceManager.GetString("HostAndHostessExcelImportEndedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import of the hosts and hostesses ended, thank you for your patience.
        /// </summary>
        public static string HostAndHostessExcelImportEndedText {
            get {
                return ResourceManager.GetString("HostAndHostessExcelImportEndedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import of the hosts and hostesses in progress....
        /// </summary>
        public static string HostAndHostessExcelImportPrincipalMessage {
            get {
                return ResourceManager.GetString("HostAndHostessExcelImportPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import of the hosts and hostesses in progress, please wait until the message sginaling the end of import appears..
        /// </summary>
        public static string HostAndHostessExcelImportSecondaryMessage {
            get {
                return ResourceManager.GetString("HostAndHostessExcelImportSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importation template for hosts and hostesses.
        /// </summary>
        public static string HostAndHostessExcelImportTemplateCaption {
            get {
                return ResourceManager.GetString("HostAndHostessExcelImportTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importation of hosts and hostesses from an Excel file, column order should be:
        ///Firstname, Lastname, Cellphone, Sex (F/M), E-mail, Adress, Zipcode, City, Country, Paycheck number, Birth city, Birth date (ex : 5 February 1982), Social security number, Height, Pants size, Shirt size, Shoe size, Car (Yes/No), Driver licence (Yes/No), English (Yes/No), German (Yes/No), Spanish (Yes/No), Italian (Yes/No), Other languages, Profile street (Yes/No), Profile event (Yes/No), Profile permanent (Yes/No).
        /// </summary>
        public static string HostAndHostessExcelImportTemplateText {
            get {
                return ResourceManager.GetString("HostAndHostessExcelImportTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host or hostess.
        /// </summary>
        public static string HostOrHostess {
            get {
                return ResourceManager.GetString("HostOrHostess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving the host or hostess in progress....
        /// </summary>
        public static string HostOrHostessArchivePrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessArchivePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the host or the hostess is being archived.
        /// </summary>
        public static string HostOrHostessArchiveSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessArchiveSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete host/hostess.
        /// </summary>
        public static string HostOrHostessConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("HostOrHostessConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected host/hostess ?.
        /// </summary>
        public static string HostOrHostessConfirmDeleteText {
            get {
                return ResourceManager.GetString("HostOrHostessConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the host/hostess in progress....
        /// </summary>
        public static string HostOrHostessCreationPrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessCreationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host/hostess is currently created and saved in the database, please wait until this window closes automatically.
        /// </summary>
        public static string HostOrHostessCreationSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessCreationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of the host/hostess in progress....
        /// </summary>
        public static string HostOrHostessDeletionPrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessDeletionPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host/hostess is currently deleted, please wait until this window closes automatically.
        /// </summary>
        public static string HostOrHostessDeletionSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessDeletionSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit of the host/hostess in progress....
        /// </summary>
        public static string HostOrHostessEditionPrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessEditionPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host/hostess is currently modified and saved in the database, please wait until this window closes automatically.
        /// </summary>
        public static string HostOrHostessEditionSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessEditionSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch emailing default application...
        /// </summary>
        public static string HostOrHostessEmailPrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessEmailPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an emailing application is installed on your machine, the application is launching, please wait.
        /// </summary>
        public static string HostOrHostessEmailSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessEmailSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host or hostess&apos; first name.
        /// </summary>
        public static string HostOrHostessFirstName {
            get {
                return ResourceManager.GetString("HostOrHostessFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host or hostess ID.
        /// </summary>
        public static string HostOrHostessID {
            get {
                return ResourceManager.GetString("HostOrHostessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host or hostess&apos; last name.
        /// </summary>
        public static string HostOrHostessLastName {
            get {
                return ResourceManager.GetString("HostOrHostessLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Skype application....
        /// </summary>
        public static string HostOrHostessPhonePrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessPhonePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Skype is installed on your machine, the application is launching, please wait.
        /// </summary>
        public static string HostOrHostessPhoneSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessPhoneSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the photo ?.
        /// </summary>
        public static string HostOrHostessPhotoConfirmDelete {
            get {
                return ResourceManager.GetString("HostOrHostessPhotoConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of the deletion of the photo.
        /// </summary>
        public static string HostOrHostessPhotoConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("HostOrHostessPhotoConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration the host or hostess in progress....
        /// </summary>
        public static string HostOrHostessRestorePrincipalMessage {
            get {
                return ResourceManager.GetString("HostOrHostessRestorePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the host or the hostess is being restored .
        /// </summary>
        public static string HostOrHostessRestoreSecondaryMessage {
            get {
                return ResourceManager.GetString("HostOrHostessRestoreSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a host or hostess.
        /// </summary>
        public static string HostOrHostessSelectedError {
            get {
                return ResourceManager.GetString("HostOrHostessSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No host or hostess selected.
        /// </summary>
        public static string HostOrHostessSelectedErrorCaption {
            get {
                return ResourceManager.GetString("HostOrHostessSelectedErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host and hostesses.
        /// </summary>
        public static string HostsAndHostesses {
            get {
                return ResourceManager.GetString("HostsAndHostesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while actualizing the hosts and hostesses from database.
        /// </summary>
        public static string HostsAndHostessesActualizationErrorCaption {
            get {
                return ResourceManager.GetString("HostsAndHostessesActualizationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of the hosts and hostesses statement in progress....
        /// </summary>
        public static string HostsAndHostessesExcelGenerationPrincipalMessage {
            get {
                return ResourceManager.GetString("HostsAndHostessesExcelGenerationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait during the generation of the hosts and hostesses statement until Microsoft Excel® is opened.
        /// </summary>
        public static string HostsAndHostessesExcelGenerationSecondaryMessage {
            get {
                return ResourceManager.GetString("HostsAndHostessesExcelGenerationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived hosts and hostesses....
        /// </summary>
        public static string HostsAndHostessesShowArchivedPrincipalMessage {
            get {
                return ResourceManager.GetString("HostsAndHostessesShowArchivedPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment of the archived hosts and hostesses, please wait until this window closes.
        /// </summary>
        public static string HostsAndHostessesShowArchivedSecondaryMessage {
            get {
                return ResourceManager.GetString("HostsAndHostessesShowArchivedSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress hosts and hostesses....
        /// </summary>
        public static string HostsAndHostessesShowInProgressPrincipalMessage {
            get {
                return ResourceManager.GetString("HostsAndHostessesShowInProgressPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment of the in progress hosts and hostesses, please wait until this window closes.
        /// </summary>
        public static string HostsAndHostessesShowInProgressSecondaryMessage {
            get {
                return ResourceManager.GetString("HostsAndHostessesShowInProgressSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts and hostesses statement.
        /// </summary>
        public static string HostsAndHostessesStatement {
            get {
                return ResourceManager.GetString("HostsAndHostessesStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts and hostesses statement not generated.
        /// </summary>
        public static string HostsAndHostessesStatementExcelGenerationFailedCaption {
            get {
                return ResourceManager.GetString("HostsAndHostessesStatementExcelGenerationFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hosts and hostesses statement could not have been generated. If this happens again, please contact the client support..
        /// </summary>
        public static string HostsAndHostessesStatementExcelGenerationFailedText {
            get {
                return ResourceManager.GetString("HostsAndHostessesStatementExcelGenerationFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id paycheck.
        /// </summary>
        public static string IdPaycheck {
            get {
                return ResourceManager.GetString("IdPaycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Excel.
        /// </summary>
        public static string ImportHostAndHostessFromExcel {
            get {
                return ResourceManager.GetString("ImportHostAndHostessFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birth date, please verify.
        /// </summary>
        public static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birth date.
        /// </summary>
        public static string InvalidBirthDateCaption {
            get {
                return ResourceManager.GetString("InvalidBirthDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non conform email address, please enter a valid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmailCaption {
            get {
                return ResourceManager.GetString("InvalidEmailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel® could not be started. Check that your Office installation is correct.
        /// </summary>
        public static string MicrosoftExcelNotFound {
            get {
                return ResourceManager.GetString("MicrosoftExcelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel® error.
        /// </summary>
        public static string MicrosoftExcelNotFoundCaption {
            get {
                return ResourceManager.GetString("MicrosoftExcelNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word® could not be started. Check that your Office installation is correct.
        /// </summary>
        public static string MicrosoftWordNotFound {
            get {
                return ResourceManager.GetString("MicrosoftWordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word® error.
        /// </summary>
        public static string MicrosoftWordNotFoundCaption {
            get {
                return ResourceManager.GetString("MicrosoftWordNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing date selection.
        /// </summary>
        public static string MissingSelectedDateErrorCaption {
            get {
                return ResourceManager.GetString("MissingSelectedDateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date not selected, please verify.
        /// </summary>
        public static string MissingSelectedDateErrorText {
            get {
                return ResourceManager.GetString("MissingSelectedDateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive of the mission in progress....
        /// </summary>
        public static string MissionArchivePrincipalMessage {
            get {
                return ResourceManager.GetString("MissionArchivePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait during the archive and the save in the database of the mission.
        /// </summary>
        public static string MissionArchiveSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionArchiveSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected mission?.
        /// </summary>
        public static string MissionConfirmDelete {
            get {
                return ResourceManager.GetString("MissionConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete mission.
        /// </summary>
        public static string MissionConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("MissionConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the mission in progress....
        /// </summary>
        public static string MissionCreationPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionCreationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mission is currently created and saved in the database, please wait until this window closes automatically.
        /// </summary>
        public static string MissionCreationSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionCreationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of the mission in progress....
        /// </summary>
        public static string MissionDeletionPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionDeletionPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mission is currently deleted, please wait until this window closes automatically.
        /// </summary>
        public static string MissionDeletionSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionDeletionSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplication of the mission in progress ....
        /// </summary>
        public static string MissionDuplicationPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionDuplicationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the mission is duplicated and saved to the database until this window is closed.
        /// </summary>
        public static string MissionDuplicationSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionDuplicationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition of the mission in progress....
        /// </summary>
        public static string MissionEditionPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionEditionPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mission is currently modified and saved in the database, please wait until this window closes automatically.
        /// </summary>
        public static string MissionEditionSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionEditionSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed.
        /// </summary>
        public static string MissionLegendBilled {
            get {
                return ResourceManager.GetString("MissionLegendBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string MissionLegendCreated {
            get {
                return ResourceManager.GetString("MissionLegendCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string MissionLegendDeclined {
            get {
                return ResourceManager.GetString("MissionLegendDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string MissionLegendDone {
            get {
                return ResourceManager.GetString("MissionLegendDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, 
        ///
        ///Please find attached the asked mission.
        ///
        ///Regards,.
        /// </summary>
        public static string MissionMailBody {
            get {
                return ResourceManager.GetString("MissionMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration of the mission in progress....
        /// </summary>
        public static string MissionRestorePrincipalMessage {
            get {
                return ResourceManager.GetString("MissionRestorePrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait during the restauration and the save in the database of the mission.
        /// </summary>
        public static string MissionRestoreSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionRestoreSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while actualizing the missions from database.
        /// </summary>
        public static string MissionsActualizationErrorCaption {
            get {
                return ResourceManager.GetString("MissionsActualizationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to show all the missions ?.
        /// </summary>
        public static string MissionsConfirmShowAll {
            get {
                return ResourceManager.GetString("MissionsConfirmShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all the missions.
        /// </summary>
        public static string MissionsConfirmShowAllCaption {
            get {
                return ResourceManager.GetString("MissionsConfirmShowAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created missions.
        /// </summary>
        public static string MissionsCreated {
            get {
                return ResourceManager.GetString("MissionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select an mission.
        /// </summary>
        public static string MissionSelectedError {
            get {
                return ResourceManager.GetString("MissionSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mission selected.
        /// </summary>
        public static string MissionSelectedErrorCaption {
            get {
                return ResourceManager.GetString("MissionSelectedErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of the missions statement in progress....
        /// </summary>
        public static string MissionsExcelGenerationPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionsExcelGenerationPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait during the generation of the missions statement until Microsoft Excel® is opened.
        /// </summary>
        public static string MissionsExcelGenerationSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionsExcelGenerationSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualization of the archived missions....
        /// </summary>
        public static string MissionsShowArchivedPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionsShowArchivedPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualization of the archived missions from the database, please wait until this window closes automatically. This operation can take a while.
        /// </summary>
        public static string MissionsShowArchivedSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionsShowArchivedSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed missions.
        /// </summary>
        public static string MissionsShowArchives {
            get {
                return ResourceManager.GetString("MissionsShowArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress missions.
        /// </summary>
        public static string MissionsShowInProgress {
            get {
                return ResourceManager.GetString("MissionsShowInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualization of the in progress missions....
        /// </summary>
        public static string MissionsShowInProgressPrincipalMessage {
            get {
                return ResourceManager.GetString("MissionsShowInProgressPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualization of the in progress missions from the database, please wait until this window closes automatically. This operation can take a while.
        /// </summary>
        public static string MissionsShowInProgressSecondaryMessage {
            get {
                return ResourceManager.GetString("MissionsShowInProgressSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The missions statement could not have been generated. If this happens again, please contact the client support..
        /// </summary>
        public static string MissionsStatementExcelGenerationFailed {
            get {
                return ResourceManager.GetString("MissionsStatementExcelGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions statement not generated.
        /// </summary>
        public static string MissionsStatementExcelGenerationFailedCaption {
            get {
                return ResourceManager.GetString("MissionsStatementExcelGenerationFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject of the mission.
        /// </summary>
        public static string MissionSubject {
            get {
                return ResourceManager.GetString("MissionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non numerical expression, please correct the value.
        /// </summary>
        public static string NonNumericExpression {
            get {
                return ResourceManager.GetString("NonNumericExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non numerical expression.
        /// </summary>
        public static string NonNumericExpressionCaption {
            get {
                return ResourceManager.GetString("NonNumericExpressionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoVATMention {
            get {
                return ResourceManager.GetString("NoVATMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening the software, please wait....
        /// </summary>
        public static string OpenSoftPrincipalMessage {
            get {
                return ResourceManager.GetString("OpenSoftPrincipalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions, hosts and hostesses, clients and settings loading from the database, this operation can take a few minutes.
        /// </summary>
        public static string OpenSoftSecondaryMessage {
            get {
                return ResourceManager.GetString("OpenSoftSecondaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        public static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos directory.
        /// </summary>
        public static string PhotosDirectory {
            get {
                return ResourceManager.GetString("PhotosDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while modifying the photos directory.
        /// </summary>
        public static string PhotosDirectoryModificationErrorCaption {
            get {
                return ResourceManager.GetString("PhotosDirectoryModificationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a date.
        /// </summary>
        public static string PickDate {
            get {
                return ResourceManager.GetString("PickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post box.
        /// </summary>
        public static string PostBox {
            get {
                return ResourceManager.GetString("PostBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving.
        /// </summary>
        public static string QuitWithoutSaving {
            get {
                return ResourceManager.GetString("QuitWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving.
        /// </summary>
        public static string QuitWithoutSavingCaption {
            get {
                return ResourceManager.GetString("QuitWithoutSavingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to quit without saving ?.
        /// </summary>
        public static string QuitWithoutSavingMessage {
            get {
                return ResourceManager.GetString("QuitWithoutSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required fields.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research a client.
        /// </summary>
        public static string ResearchClient {
            get {
                return ResourceManager.GetString("ResearchClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research an host/hostess.
        /// </summary>
        public static string ResearchHostOrHostess {
            get {
                return ResourceManager.GetString("ResearchHostOrHostess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research an mission.
        /// </summary>
        public static string ResearchMission {
            get {
                return ResourceManager.GetString("ResearchMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources not found. Please, resinstall the software..
        /// </summary>
        public static string ResourcesNotFound {
            get {
                return ResourceManager.GetString("ResourcesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources non trouvées..
        /// </summary>
        public static string ResourcesNotFoundCaption {
            get {
                return ResourceManager.GetString("ResourcesNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and quit.
        /// </summary>
        public static string SaveAndQuit {
            get {
                return ResourceManager.GetString("SaveAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to edit the settings?.
        /// </summary>
        public static string SettingsConfirmEdit {
            get {
                return ResourceManager.GetString("SettingsConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string SettingsConfirmEditCaption {
            get {
                return ResourceManager.GetString("SettingsConfirmEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        public static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants.
        /// </summary>
        public static string SizePants {
            get {
                return ResourceManager.GetString("SizePants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt.
        /// </summary>
        public static string SizeShirt {
            get {
                return ResourceManager.GetString("SizeShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string SizeShoes {
            get {
                return ResourceManager.GetString("SizeShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social security number.
        /// </summary>
        public static string SocialSecurityNumber {
            get {
                return ResourceManager.GetString("SocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZadGestion.
        /// </summary>
        public static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing subject.
        /// </summary>
        public static string SubjectMissingCaption {
            get {
                return ResourceManager.GetString("SubjectMissingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add a subject in the corresponding field.
        /// </summary>
        public static string SubjectMissingText {
            get {
                return ResourceManager.GetString("SubjectMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word® template not found, please contact the technical service.
        /// </summary>
        public static string TemplateWordNotFound {
            get {
                return ResourceManager.GetString("TemplateWordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found.
        /// </summary>
        public static string TemplateWordNotFoundCaption {
            get {
                return ResourceManager.GetString("TemplateWordNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT number.
        /// </summary>
        public static string VATNumber {
            get {
                return ResourceManager.GetString("VATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word® generation.
        /// </summary>
        public static string WordGeneration {
            get {
                return ResourceManager.GetString("WordGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word® missing.
        /// </summary>
        public static string WordNotPresentErrorCaption {
            get {
                return ResourceManager.GetString("WordNotPresentErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word® is missing, please install it to use ZadGestion.
        /// </summary>
        public static string WordNotPresentErrorText {
            get {
                return ResourceManager.GetString("WordNotPresentErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL.
        /// </summary>
        public static string XL {
            get {
                return ResourceManager.GetString("XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XS.
        /// </summary>
        public static string XS {
            get {
                return ResourceManager.GetString("XS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXL.
        /// </summary>
        public static string XXL {
            get {
                return ResourceManager.GetString("XXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXS.
        /// </summary>
        public static string XXS {
            get {
                return ResourceManager.GetString("XXS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years old.
        /// </summary>
        public static string YearsOld {
            get {
                return ResourceManager.GetString("YearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZadGestion already running.
        /// </summary>
        public static string ZadGestionRunningErrorCaption {
            get {
                return ResourceManager.GetString("ZadGestionRunningErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZadGestion is already running. To avoid any conflicts, it is not possible to open two instances of the software at the same time.
        /// </summary>
        public static string ZadGestionRunningErrorText {
            get {
                return ResourceManager.GetString("ZadGestionRunningErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
